services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: letspay # creates DB with this name at init
      POSTGRES_USER: letsuser # superuser (needs to match application.properties)
      POSTGRES_PASSWORD: letspassword
      PGDATA: /data/letspay
    volumes:
      - db:/data/postgres
    ports:
      - "5372:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
    driver: local